spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: guest
    password: password
    url: jdbc:mysql://localhost:3306/laravel

mybatis:
  type-aliases-package: com.example.api.models
  mapper-locations: classpath:mybatis/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
